framework:
  assets:
      packages:
          captures:
              base_path: '%kernel.project_dir%/public'
              version_strategy: 'App\Asset\VersionStrategy\FileTimestampVersionStrategy'