twig:
    form_themes: ['tailwind_2_layout.html.twig']
    file_name_pattern: '*.twig'
    globals:
        supported_locales: '%supported_locales%'
        plausible_host: '%env(PLAUSIBLE_HOST)%'
        plausible_domain: '%env(PLAUSIBLE_DOMAIN)%'

when@test:
    twig:
        strict_variables: true
