controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    prefix: /{_locale}
    requirements:
        _locale: 'en|fr|ru|uk'


index:
    path: /
    controller: App\Controller\IndexController::index